### ISSUE TITLE
Double sendBody in DataResponse

### ISSUE THREAD

**Issue by enozero** [envoy/Ambassador#22]
Just curious, is this supposed to call `sendBody` with an empty `Data`? I don't see any comments around it why it would do that.

https://github.com/envoy/Ambassador/blob/master/Ambassador/Responses/DataResponse.swift#L81

```
            if !data.isEmpty {
                sendBody(data)
            }
-->         sendBody(Data())
```

**Comment by enozero** [comment]
Nevermind... https://github.com/envoy/Ambassador/issues/19 answered my question.

**Comment by fangpenlin** [comment]
@enozero sending an empty data means EOF (end of file), or close the connection.

As you may want to send data chunks, at one point you want to tell Embassy to close the connection, then you send an empty data.

**Comment by enozero** [comment]
That makes perfect sense. Thanks!
