### ISSUE TITLE
App Lockup

### ISSUE THREAD

**Issue by skram** [envoy/Ambassador#23]
Using the exact example code, after running the server..the app freezes, but the server is still accessible. Any ideas as to what may be going wrong? If I comment out `loop.runForever()` it doesn't happen..but the server doesn't work. using Xcode 9 on iOS 11 Swift 3.

```import Embassy
import Embassy
import EnvoyAmbassador

let loop = try! SelectorEventLoop(selector: try! KqueueSelector())
let router = Router()
let server = DefaultHTTPServer(eventLoop: loop, port: 8080, app: router.app)

router["/api/v2/users"] = DelayResponse(JSONResponse(handler: { _ -> Any in
    return [
        ["id": "01", "name": "john"],
        ["id": "02", "name": "tom"]
    ]
}))

// Start HTTP server to listen on the port
try! server.start()

// Run event loop
loop.runForever()```

**Comment by fangpenlin** [comment]
@skram Like `runForever` implies, it blocks current thread you're running it on. So if you want the UI event loop works along with the Embassy server, please use another thread, like NSThread.

**Comment by skram** [comment]
@fangpenlin mind sharing an example of how to do so with above as an example? having difficulty with this. Much appreciated.

**Comment by fangpenlin** [comment]
@skram you can see how we use NSThread to run it in a separate thread here in this article

https://envoy.engineering/embedded-web-server-for-ios-ui-testing-8ff3cef513df

**Comment by skram** [comment]
Thanks. Actually, I just resolved it prior to your response with the same resource link. Thanks.
