### ISSUE TITLE
Possible to serve JSON files?

### ISSUE THREAD

**Issue by damianesteban** [envoy/Ambassador#26]
Ambassador is a great project - I've been using it for testing and I love it.

Is it possible to serve JSON directly from a file, similar to how [json-server](https://github.com/typicode/json-server) works?

**Comment by fangpenlin** [comment]
@damianesteban Thank you for so much! Really glad to hear 😄 🙌

Yes, it's possible, that's not a build-in function, but you can do it manually with `JSONResponse`, like this

```
router["/users/([0-9]+)"] = JSONResponse(handler: { environ -> Any in
    let captures = environ["ambassador.router_captures"] as! [String]
    let id = captures[0]
    let users = [
        "1": [
            "name": "john"
        ]
    ]
    return users[id]
})
```

or you can also define your own Response, which reads JSON files, parses URL parameters and return them accordingly. I think reference to how `JSONResponse` works

https://github.com/envoy/Ambassador/blob/master/Ambassador/Responses/JSONResponse.swift#L14-L71

could be a good start.

**Comment by damianesteban** [comment]
Perfect! Thank you.
