### ISSUE TITLE
Update cocoapods version

### ISSUE THREAD

**Issue by GeroHerkenrath** [envoy/Ambassador#34]
Aloha Envoy team!

The cocoapods version is still a tiny bit behind, it doesn't include @fangpenlin's PR #28.
Since my project uses cocoapods I still get a warning during builds (that's the only one, so kinda prominent).

I had actually already forked the repo and wanted to fix the deprecated call to `characters`, I was really confused when master already had the latest Swift syntax. 😸

Maybe one of you can quickly do a tag, version bump etc. and push to the cocoapods spec repo?

Thanks a lot, your Embassy & Ambassador have really helped me a lot in testing (and since it's all swift I can keep my repo nice and clean!).

**Comment by fangpenlin** [comment]
Hi @GeroHerkenrath, thanks for letting us know! Sorry we are too busy forgot to make a new release. I just made a 4.0.2 release. Also thanks for the kind words 😄
